on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        continue-on-error: false
      
      - name: install node dependencies
        run: npm install
        continue-on-error: false
      
      - name: compile and build site structure
        run: npm run build
        continue-on-error: false
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: copy build files to remote site host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GDC_SITE_HOST_MACHINE }}
          source: 'build/*'
          target: '/web/gdc'
          rm: true
          key: ${{ secrets.GDC_SITE_HOST_MACHINE_PRIVATE_LOGIN_KEY }}
    
