on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        continue-on-error: false
      
      - name: install node dependencies
        run: npm install
        continue-on-error: false
      
      - name: compile and build site structure
        run: npm run build
        continue-on-error: false
      
      - uses: actions/upload-artifact@v1
        with:
          name: site-build
          path: build
        continue-on-error: false
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - run: mkdir -p site-build
        continue-on-error: false
      
      - uses: actions/download-artifact@v1
        with:
          name: site-build
          path: site-build
        continue-on-error: false
      
      - name: clean remote site host file host directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GDC_SITE_HOST_MACHINE_IP }}
          username: ${{ secrets.GDC_SITE_HOST_MACHINE_LOGIN_USERNAME }}
          script: rm -rf ${{ secrets.GDC_SITE_HOST_MACHINE_FILE_HOST_DIRECTORY }}/*
        continue-on-error: false

      - name: copy build files to remote site host file host directory
        uses: appleboy/scp-action@master
        with:
          overwrite: true
          strip_components: 1

          source: 'site-build/*'
          target: ${{ secrets.GDC_SITE_HOST_MACHINE_FILE_HOST_DIRECTORY }}
          tar_tmp_path: ${{ secrets.GDC_SITE_HOST_MACHINE_FILE_HOST_DIRECTORY }}

          host: ${{ secrets.GDC_SITE_HOST_MACHINE_IP }}
          username: ${{ secrets.GDC_SITE_HOST_MACHINE_LOGIN_USERNAME }}
          key: ${{ secrets.GDC_SITE_HOST_MACHINE_LOGIN_PRIVATE_SSH_KEY }}
    
